# Generated by Django 4.2.7 on 2025-08-22 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Unique product name', max_length=255, unique=True)),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('min_threshold', models.PositiveIntegerField(default=10, help_text='Minimum stock threshold for alerts')),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
    ]
